formatter: markdown table

header-from: ../../docs/header.md

output:
  file: ./README.md
  mode: inject

content: |-
  {{ .Header }}

  {{ include "../../docs/tooling.md" }}

  {{ include "../../docs/setup.md" }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}
