name: Bash Scripts CI (🐚)

on:
  push:
    paths:
      - "./scripts/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies (🐚)
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck bats
          wget https://github.com/mvdan/sh/releases/latest/download/shfmt_linux_amd64 -O shfmt
          chmod +x shfmt
          sudo mv shfmt /usr/local/bin/shfmt
      - name: Lint and format (🐚)
        run: |
          shfmt -i 2 -d -s -ci .
          shellcheck ./scripts
      - name: Run tests (🐚)
        run: bats ./scripts/test
